INSERT INTO movie (title, release_year, genre, duration_in_minutes, format, age_limit, language) VALUES
('Inception', 2010, 'SCIENCE_FICTION', 148, 'TWO_DIMENSIONAL', 'ELEVEN_PLUS', 'ENGLISH'),
('The Notebook', 2004, 'ROMANCE', 123, 'TWO_DIMENSIONAL', 'SEVEN_PLUS', 'ENGLISH'),
('Get Out', 2017, 'HORROR', 104, 'TWO_DIMENSIONAL', 'FIFTEEN_PLUS', 'ENGLISH'),
('Mad Max: Fury Road', 2015, 'ACTION', 120, 'THREE_DIMENSIONAL', 'FIFTEEN_PLUS', 'ENGLISH'),
('Badehotellet: Special', 2022, 'ROMANCE', 95, 'TWO_DIMENSIONAL', 'ALL', 'DANISH'),
('Planet X', 2024, 'SCIENCE_FICTION', 132, 'THREE_DIMENSIONAL', 'ELEVEN_PLUS', 'ENGLISH'),
('Night Train', 2021, 'ACTION', 110, 'TWO_DIMENSIONAL', 'SEVEN_PLUS', 'DANISH'),
('Haunted Hall', 2019, 'HORROR', 99, 'TWO_DIMENSIONAL', 'FIFTEEN_PLUS', 'ENGLISH'),
('Titanic', 1997, 'ROMANCE', 195, 'TWO_DIMENSIONAL', 'ELEVEN_PLUS', 'ENGLISH'),
('Druk', 2020, 'ACTION', 117, 'TWO_DIMENSIONAL', 'ELEVEN_PLUS', 'DANISH');